### ISSUE TITLE
TODO : 2016.06.30 ~

### ISSUE THREAD

**Issue by mamoru2110** [mamoru2110/mamoru2110.github.io#1]
## Posts
- [ ] Delete hatena markdown.
- [ ] Move images to Flickr.

## Web Site
- [ ] Decrease pagination number.
- [ ] Move sidebar to left.
- [ ] Improve tag display.
- [ ] Polish css.
- [ ] Add Sitemap for Search Console.

**Comment by mamoru2110** [comment]
#2c82da4 is Release for ...

- Posts
  - Delete hatena markdown.
  - Delete links to hatena.

**Comment by mamoru2110** [comment]
Done.

- Web site
  - Shorten the list pagination.

and released by commit ae6fe06089634b4d300f4812ffaae9426c2c193d
